config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "main#index"

  get 'help', to: 'help#index'

  get 'settings', to: 'users#settings'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def settings; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_icon(icon, classes: nil)
    classes ||= ""
    render "icons/#{icon}", classes: classes
  end

  def is_help_path
    controller_name == 'components' && action_name == 'index'
  end
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/help/index.html.erb
<% content_for :title, "Documentation | Webshop" %>

<div class="relative mx-auto flex w-full max-w-8xl flex-auto justify-center sm:px-2 lg:px-8 xl:px-12">
  Help Page
</div>

app/views/icons/_google.html.erb
<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16" class="<%= classes %>" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z"></path></svg>

app/views/icons/_hamburger.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
  <line x1="4" y1="6" x2="20" y2="6"></line>
  <line x1="4" y1="12" x2="20" y2="12"></line>
  <line x1="4" y1="18" x2="20" y2="18"></line>
</svg>

app/views/layouts/_devise.html.erb
<div class="my-6 min-h-[calc(100vh-73px)] flex w-full flex-col items-center justify-center gap-6 max-w-[320px] mx-auto">
  <%= yield %>
</div>

app/views/layouts/_header.html.erb
<header class="sticky inset-x-0 top-0 z-20">
  <div class="max-w-7xl mx-auto flex justify-between py-16">
    <%= link_to 'Help', help_path, class: class_names("btn btn-link text-2xl", "bg-gray-100 text-gray-900": is_help_path) %>
    <% if user_signed_in? %>
      <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-link text-2xl" %>
    <% else %>
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-link text-2xl' %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title><%= content_for(:title) || "Photoworks" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="flex flex-col min-h-screen">
    <%= render 'layouts/header' %>
    <% if notice.present? %>
      <p class="notice max-w-7xl mx-auto text-center"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert max-w-7xl mx-auto text-center"><%= alert %></p>
    <% end %>
    <% if devise_controller? %>
      <%= render 'layouts/devise' %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/main/index.html.erb
<div class="max-w-7xl w-full mx-auto py-16">
  <%= content_tag(:div, "", data: {
    controller: "svelte"
  }) %>
</div>